import { expect, test } from 'bun:test';
import { isAuditLogQuery, isWriteQuery } from '../../src/storage/audit-log.ts';

test('audit query parsing ignores leading SQL comments for write detection', () => {
  expect(isWriteQuery('/* generated by drizzle */\nUPDATE settings SET value = ?')).toBe(true);
  expect(isWriteQuery('-- read path\nselect * from settings')).toBe(false);
});

test('audit log table detection handles sqlite write variants', () => {
  expect(isAuditLogQuery('insert or replace into main."audit_log" values (?)')).toBe(true);
  expect(isAuditLogQuery('/* trace */ update [audit_log] set who = ?')).toBe(true);
  expect(isAuditLogQuery('delete from `main`.`settings` where key = ?')).toBe(false);
});
